project_id = "mrnjywxdrlplpphdjyvf"

[functions.scan-receipt]
verify_jwt = true

[functions.export-user-data]
verify_jwt = true

[functions.process-recurring-expenses]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
